=head1 NAME

webapp/README

=head1 DESCRIPTION

This is the README pod for the application code base 'webapp'.  This is a Catalyst application that already has a few nice things built into the Model (a base database), the Controllers (some init/admin page possibilities) and login utilities, as well as a Template Toolkit front end based off of Twitter Bootstrap.

=head1 SETUP

Getting this started is a little bit more painful than I currently want it to be.  I need to test the following on a clean box:

perl Makefile.PL

make
make installdeps
make install

** Run!

I coded this with postgresql in mind.  The problem is the default values for timestamps currently in the Model ResultSet classes.  it is set to \"now()" which will break in many databases, I think.

=head2 cpan install

=over 4

=item Catalyst::Plugin::Session::Store::Memcached

=item Facebook::Graph

=back

=head1 AUTHOR

Paul Salcido, paulsalcido.79@gmail.com

=head1 LICENSE

This library is free software. You can redistribute it and/or modify it under the same terms as Perl itself.

=cut
