package webapp::Model::WebAppDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config();

=head1 NAME

webapp::Model::WebAppDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<webapp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<webapp::Model::WebAppDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Paul Salcido

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
